### ISSUE TITLE
ETH & ERC20 smart contract interaction allowance - contract UX improvement

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/EthereumBridge#15]
Currently every time Alice wants to swap ERC20 to secretERC20, she needs to first approve the bridge deposit contract to spend up to a limit and then sign the actual transaction

In all smart contract interactions, Alice would initiatlize the bridge deposit contract once to allow the contract to spend up to X ERC20 and then every following TX would just need Alice's signature. This way we reduce required steps from 2 to 1. 

Here's an example:
First time trading BAL (ERC20) on Balancer. Unlock = authorize
![image](https://user-images.githubusercontent.com/15679491/100901608-ff1e2500-3491-11eb-82b9-89b33c4341a0.png)

Metamask signing screen
![image](https://user-images.githubusercontent.com/15679491/100901660-10ffc800-3492-11eb-8f7e-423c372b4612.png)
Advanced view where you can set the spending limit
![image](https://user-images.githubusercontent.com/15679491/100901714-24ab2e80-3492-11eb-92a1-844ed594d7f5.png)

**Comment by Cashmaney** [comment]
@cankisagun Can you move this issue to the frontend repo? This is just a UX thing

**Comment by cankisagun** [comment]
moving to frontend repo
